import { DataTypes } from "sequelize";
import { sequelize } from "../database/database.js";

export const Nacimiento = sequelize.define("nacimiento", {
    id: {
        type: DataTypes.INTEGER,
        primaryKey: true,
        autoIncrement: true,
    },
    identificador: { type: DataTypes.TEXT, unique: true },
    ssa: { type: DataTypes.TEXT },
    curp: { type: DataTypes.TEXT },
    foja: { type: DataTypes.TEXT },
    pais: { type: DataTypes.TEXT },
    sexo: { type: DataTypes.TEXT },
    tomo: { type: DataTypes.TEXT },
    folio: { type: DataTypes.TEXT },
    libro: { type: DataTypes.TEXT },
    madre: { type: DataTypes.TEXT },
    padre: { type: DataTypes.TEXT },
    sello: { type: DataTypes.TEXT },
    cadena: { type: DataTypes.TEXT },
    noActa: { type: DataTypes.TEXT },
    nombre: { type: DataTypes.TEXT },
    actaBis: { type: DataTypes.TEXT },
    paisTxt: { type: DataTypes.TEXT },
    curpAux1: { type: DataTypes.TEXT },
    curpAux2: { type: DataTypes.TEXT },
    nacMADRE: { type: DataTypes.TEXT },
    nacPADRE: { type: DataTypes.TEXT },
    curpMADRE: { type: DataTypes.TEXT },
    curpPADRE: { type: DataTypes.TEXT },
    estadoNac: { type: DataTypes.TEXT },
    estadoReg: { type: DataTypes.TEXT },
    localidad: { type: DataTypes.TEXT },
    municipio: { type: DataTypes.TEXT },
    oficialia: { type: DataTypes.TEXT },
    numeroActa: { type: DataTypes.TEXT },
    valorMovim: { type: DataTypes.TEXT },
    vivoMuerto: { type: DataTypes.TEXT },
    codigoCivil: { type: DataTypes.TEXT },
    identElectr: { type: DataTypes.TEXT },
    nacMadreTxt: { type: DataTypes.TEXT },
    nacPadreTxt: { type: DataTypes.TEXT },
    tipoPersona: { type: DataTypes.TEXT },
    anioRegistro: { type: DataTypes.TEXT },
    municipioNac: { type: DataTypes.TEXT },
    municipioReg: { type: DataTypes.TEXT },
    nacionalidad: { type: DataTypes.TEXT },
    fechaRegistro: { type: DataTypes.TEXT },
    transcripcion: { type: DataTypes.TEXT },
    primerApellido: { type: DataTypes.TEXT },
    estadoNacNombre: { type: DataTypes.TEXT },
    estadoRegNombre: { type: DataTypes.TEXT },
    fechaNacimiento: { type: DataTypes.TEXT },
    municipioNombre: { type: DataTypes.TEXT },
    nacionalidadTxt: { type: DataTypes.TEXT },
    notasMarginales: { type: DataTypes.TEXT },
    oficialiaNombre: { type: DataTypes.TEXT },
    segundoApellido: { type: DataTypes.TEXT },
    nacionalidadAux1: { type: DataTypes.TEXT },
    nacionalidadAux2: { type: DataTypes.TEXT },
    estadoRegNacNombre: { type: DataTypes.TEXT },
    municipioNacNombre: { type: DataTypes.TEXT },
    municipioRegNombre: { type: DataTypes.TEXT },
    nacionalidadAux1Txt: { type: DataTypes.TEXT },
    nacionalidadAux2Txt: { type: DataTypes.TEXT },
    nombrePrimeraPersona: { type: DataTypes.TEXT },
    nombreSegundaPersona: { type: DataTypes.TEXT },
    primerApellidoPrimeraPersona: { type: DataTypes.TEXT },
    primerApellidoSegundaPersona: { type: DataTypes.TEXT },
    segundoApellidoPrimeraPersona: { type: DataTypes.TEXT },
    segundoApellidoSegundaPersona: { type: DataTypes.TEXT },
});
